services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network
  php:
    container_name: php
    build: ./etc/php/
    volumes:
      - ./src:/src
      - ./etc/php/php.ini-development:/usr/local/etc/php/php.ini
      - ./etc/php/auth.json:/root/.composer/auth.json
      - ./etc/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    tty: true
    networks:
      - network
  db:
    container_name: db
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_DATABASE: magento
      MYSQL_USER: magentouser
      MYSQL_PASSWORD: 111111
  redis:
    container_name: redis
    image: bitnami/redis:6.0
    volumes:
      - ./etc/redis/redis-data:/var/lib/redis
      - ./etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - network
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.7.0
    networks:
      - network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  varnish:
    container_name: varnish
    image: varnish:6.5
    networks:
      - network
    ports:
      - "6082:6082"
volumes:
  db_data: {}
networks:
  network:
    driver: bridge
